WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 1000
NOTE_HEIGHT = 10
SLACK = 10
SINGING_LINE_X = WINDOW_WIDTH // 4

LEAD_TIME = 3
UPDATE_FREQ = 0.05
AUDIO_BUFFER = 0.6

NOTE_SPEED = (WINDOW_WIDTH - SINGING_LINE_X) / LEAD_TIME

FONT_NAME = 'Courier New'
MIDI_DIRECTORY = 'read_midi/'
OFF_COLOR = (255, 0, 0)
ON_COLOR = (0, 255, 0)